"""All V2 figures. Regenerated from results/v2/raw/*.csv only.
   PYTHONPATH=llm/src python3 scripts/v2/generate_v2_figures.py
Captions with full parameter context go to figures/v2/CAPTIONS.md.
"""
import sys, os, json
sys.path.insert(0, "llm/src")
import numpy as np, pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from cantor_guard.cantor_barrier import build_layout, cantor_gap_list
from cantor_guard.statistics import paired_bootstrap, auc_log, pareto_front
from cantor_guard.io import FIG, V2_RAW, V2_TAB

plt.rcParams.update({"figure.dpi": 150, "font.size": 8, "axes.grid": True,
                     "grid.alpha": .25, "axes.spines.top": False,
                     "axes.spines.right": False, "legend.fontsize": 7,
                     "axes.titlesize": 9})
CAP = ["# V2 figure captions\n\nRegenerated by `scripts/v2/generate_v2_figures.py`.\n"]
def cap(name, text): CAP.append(f"\n### {name}\n\n{text}\n")
def save(fig, name):
    fig.tight_layout(); fig.savefig(FIG / name, bbox_inches="tight"); plt.close(fig)
    print("  ok", name)
def have(f): return (V2_RAW / f).exists()

COL = {"L0_none": "#888888", "L1_constant": "#d62728", "L2_central": "#ff7f0e",
       "L3_periodic": "#2ca02c", "L4_random": "#17becf", "L5_shuffled": "#9467bd",
       "L6_center_anchored": "#8c564b", "L7_cantor": "#1f77b4"}
BCOL = {k.replace("L", "B", 1): v for k, v in COL.items()}
ORDER = list(COL)

# ---------------------------------------------------------------- V2-01..04
n = 6; E0 = 1.0 / n
L = build_layout("L7_cantor", n, E0)
r = np.linspace(0, 1, 200001)

fig, ax = plt.subplots(2, 1, figsize=(9, 4.6), sharex=True)
for g in L.gaps:
    ax[0].add_patch(plt.Rectangle((g.a, g.level - .4), g.width, .8,
                                  color=plt.cm.viridis((g.level - 1) / (n - 1))))
ax[0].set_ylim(n + .6, .4); ax[0].set_ylabel("removal level $k$")
ax[0].set_yticks(range(1, n + 1))
ax[0].set_title(f"FIG V2-01  Cantor gaps to level n={n}: "
                r"$N_k=2^{k-1}$ gaps of width $w_k=3^{-k}$")
ax[0].axvline(.5, color="k", ls="--", lw=1)
ax[0].text(.5, .2, " decision boundary r=1/2", fontsize=7, va="top")
ax[1].plot(r, L.field(r), lw=.7, color="#1f77b4")
ax[1].set_xlabel("threat coordinate $r$"); ax[1].set_ylabel(r"$V'(r)$")
ax[1].set_title(r"scale-compensated field: peak of level $k$ is $3E_0(3/2)^k$")
save(fig, "figV2_01_gap_levels.png")
cap("FIG V2-01 — `figV2_01_gap_levels.png`",
    f"Cantor gap structure to level n={n} (colour = removal level) and the "
    r"resulting control field $V'(r)$. $r=1/2$ is the refusal decision "
    "boundary; the level-1 gap straddles it by construction.")

fig, ax = plt.subplots(1, 3, figsize=(11, 3.1))
for k in range(1, n + 1):
    gs = [g for g in L.gaps if g.level == k]
    xx = np.linspace(0, 1, 4001)
    Lk = build_layout("L7_cantor", n, E0)
    ax[0].plot(xx, [max([Lk.coef[i] * 6 * ((x - Lk.las[i]) / Lk.wid[i]) *
                         (1 - (x - Lk.las[i]) / Lk.wid[i])
                         if Lk.las[i] < x < Lk.lbs[i] else 0
                         for i in range(len(Lk.gaps)) if Lk.gaps[i].level == k] + [0])
                    for x in xx], lw=.8, label=f"k={k}",
               color=plt.cm.viridis((k - 1) / (n - 1)))
ax[0].set_xlabel("$r$"); ax[0].set_ylabel(r"$|V'_k(r)|$"); ax[0].legend(ncol=2)
ax[0].set_title("FIG V2-02  field by level")
ks = np.arange(1, n + 1)
ax[1].bar(ks, [E0] * n, color="#1f77b4")
ax[1].axhline(E0, color="r", ls="--", label=f"$E_0$ = {E0:.4f}")
ax[1].set_xlabel("level $k$"); ax[1].set_ylabel(r"$\sum_j\int|V'_{k,j}|$")
ax[1].set_ylim(0, E0 * 1.6); ax[1].legend()
ax[1].set_title("FIG V2-03  Theorem A: level action is constant")
pk = [L.peak_of_level(k) for k in ks]
ax[2].semilogy(ks, pk, "o-", color="#d62728")
sl = np.polyfit(ks, np.log(pk), 1)[0]
ax[2].set_xlabel("level $k$"); ax[2].set_ylabel(r"$\|V'_k\|_\infty$")
ax[2].set_title(f"FIG V2-04  Theorem B: slope={sl:.6f}, log(3/2)={np.log(1.5):.6f}")
save(fig, "figV2_02_04_theorems.png")
cap("FIG V2-02/03/04 — `figV2_02_04_theorems.png`",
    "Left: the field contributed by each removal level. Middle: Theorem A — "
    r"every level carries the same total action $E_0=B_{total}/n$. Right: "
    r"Theorem B — the peak magnitude grows exactly as $(3/2)^k$, restoring the "
    "scale law V1 normalised away. Both hold identically for every "
    "width-matched control, so neither supports a Cantor-specific claim.")

# ---------------------------------------------------------------- V2-05, 06
if have("synthetic_main.csv"):
    sy = pd.read_csv(V2_RAW / "synthetic_main.csv")
    sy["safe"] = 1 - sy.crossed.astype(float)
    fig, ax = plt.subplots(1, 2, figsize=(11, 3.6))
    for c in [c for c in sy.ctrl.unique()]:
        s = sy[sy.ctrl == c].groupby("A")["safe"].mean()
        ax[0].semilogx(s.index, s.values, "o-", ms=3, lw=1.4,
                       label=c, color=BCOL.get(c, "k"))
    ax[0].set_xlabel("attack amplitude $A$ (log)"); ax[0].set_ylabel("P(safe)")
    ax[0].legend(ncol=2, fontsize=6)
    ax[0].set_title("FIG V2-05  synthetic robustness vs log amplitude\n"
                    "(55 680 sims, 3 fields, 5 attack families)")
    KEY = ["n", "field", "A", "attack", "phase", "r0"]
    piv = sy.groupby(KEY + ["ctrl"])["safe"].mean().unstack("ctrl").dropna()
    names, mids, los, his = [], [], [], []
    for c in ["B0_none", "B1_constant", "B2_central", "B3_periodic",
              "B4_random", "B5_shuffled", "B6_center_anchored"]:
        if c not in piv: continue
        st = paired_bootstrap(piv["B7_cantor"].values, piv[c].values, seed=5)
        names.append(c.replace("B", "").replace("_", " ")); mids.append(st["mean_diff"])
        los.append(st["mean_diff"] - st["ci_lo"]); his.append(st["ci_hi"] - st["mean_diff"])
    y = np.arange(len(names))
    ax[1].errorbar(mids, y, xerr=[los, his], fmt="o", color="#1f77b4", capsize=3)
    ax[1].axvline(0, color="k", lw=1)
    ax[1].set_yticks(y); ax[1].set_yticklabels(names)
    ax[1].set_xlabel(r"$\Delta$ P(safe): Cantor $-$ control  (>0 = Cantor better)")
    ax[1].set_title("FIG V2-06  paired difference, 95% bootstrap CI")
    save(fig, "figV2_05_06_synthetic.png")
    cap("FIG V2-05/06 — `figV2_05_06_synthetic.png`",
        "Left: P(safe) against attack amplitude on a log axis; every controller "
        "collapses at large A, and the discrimination happens at A in [2,6]. "
        "Right: paired bootstrap of Cantor minus each control over 1920 matched "
        "conditions. Cantor beats none/constant/periodic but LOSES to central "
        "and to shuffled, and is indistinguishable from center-anchored "
        "(d_z=0.049) — H3 and H4 rejected in the synthetic setting.")

# ---------------------------------------------------------------- V2-07, 08
mk = "qwen2.5-0.5b-instruct"
if have(f"llm_separability_{mk}.csv"):
    sep = pd.read_csv(V2_RAW / f"llm_separability_{mk}.csv")
    ca = pd.read_csv(V2_RAW / f"llm_causal_{mk}.csv")
    fig, ax = plt.subplots(1, 2, figsize=(11, 3.4))
    for m, g in sep.groupby("method"):
        ax[0].plot(g.layer, g.cohens_d, "o-", ms=3, label=m)
    ax[0].axvline(13, color="r", ls="--", lw=1, label="selected layer 13")
    ax[0].set_xlabel("layer"); ax[0].set_ylabel("Cohen's $d$ (harmful vs harmless)")
    ax[0].legend(); ax[0].set_title("FIG V2-07  refusal-direction separability by layer")
    e = ca[ca.eps_pct == ca.eps_pct.max()]
    base = ca[ca.eps_pct == 0].groupby("layer").refusal_harmful.mean()
    p = e[e.sign == "plus"].groupby("layer").refusal_harmful.mean()
    m_ = e[e["sign"] == "minus"].groupby("layer").refusal_harmful.mean()
    ax[1].plot(base.index, base.values, "ks-", ms=4, label="no intervention")
    ax[1].plot(p.index, p.values, "^-", color="#2ca02c", ms=5, label=r"$+\epsilon v$")
    ax[1].plot(m_.index, m_.values, "v-", color="#d62728", ms=5, label=r"$-\epsilon v$")
    ax[1].axvline(13, color="r", ls="--", lw=1)
    ax[1].set_xlabel("layer"); ax[1].set_ylabel("refusal rate on harmful prompts")
    ax[1].set_ylim(0, 1); ax[1].legend()
    ax[1].set_title(r"FIG V2-08  CAUSAL validation ($\epsilon$ = 8% of act. norm)")
    save(fig, "figV2_07_08_direction.png")
    cap("FIG V2-07/08 — `figV2_07_08_direction.png`",
        "Left: separability of harmful vs harmless prompts along each estimated "
        "direction, per layer (a DIAGNOSTIC — high separability does not imply "
        "causal control). Right: the causal test that actually licenses use of "
        "the direction. At layer 13, adding the direction raises refusal on "
        "harmful prompts from 0.625 to 0.875 and subtracting it drops refusal "
        "to 0.375. This is what passes STOP CONDITION A.")

# ---------------------------------------------------------------- V2-10
fig, ax = plt.subplots(figsize=(9, 3.2))
mm = np.linspace(-8, 8, 4001)
from cantor_guard.control_baselines import make_controller
for fam in ["L1_constant", "L2_central", "L5_shuffled", "L6_center_anchored", "L7_cantor"]:
    c = make_controller(fam, n=5, B_total=1.0, eta=1.0, gamma=0.7, seed=1)
    ax.plot(mm, c.magnitude(mm), lw=1.2, label=fam, color=COL[fam])
ax.axvline(0, color="k", ls="--", lw=1); ax.set_xlabel("safety margin $m$")
ax.set_ylabel(r"$c(r(m))/\eta$"); ax.legend(ncol=3)
ax.set_title("FIG V2-10  where each controller acts (all have identical total action)")
save(fig, "figV2_10_activation_locations.png")
cap("FIG V2-10 — `figV2_10_activation_locations.png`",
    r"Control magnitude as a function of the safety margin, at matched total "
    r"action $\int c\,dr = B_{total}$. The barrier controllers are BLOCKING "
    r"controllers: past the last gap ($m\ll0$, $r\to1$) their force returns to "
    "zero, whereas constant steering keeps pushing. This structural difference "
    "dominates the LLM results.")

# ---------------------------------------------------------- V2-11..16 (LLM test)
tf = V2_RAW / f"llm_test_{mk}.csv"
if tf.exists():
    te = pd.read_csv(tf)
    h = te[te.kind == "harmful"]
    fam_order = [f for f in ORDER if f in set(te.family)]
    for regime in sorted(h.regime.unique()):
        hr = h[h.regime == regime]
        fig, ax = plt.subplots(2, 2, figsize=(11, 6.4))
        t = hr.pivot_table(index="family", columns="attack", values="asr", aggfunc="mean")
        t = t.reindex([f for f in fam_order if f in t.index])
        t.plot(kind="bar", ax=ax[0, 0], width=.8)
        ax[0, 0].set_ylabel("attack success rate"); ax[0, 0].set_xlabel("")
        ax[0, 0].legend(fontsize=6); ax[0, 0].tick_params(axis="x", rotation=35)
        ax[0, 0].set_title(f"FIG V2-11  ASR by held-out attack family [{regime}]")
        for f in fam_order:
            s = hr[hr.family == f].groupby("eps_pct").asr.mean()
            ax[0, 1].plot(s.index, s.values, "o-", ms=3, label=f, color=COL[f])
        ax[0, 1].set_xlabel(r"latent attack $\epsilon$ (% of activation norm)")
        ax[0, 1].set_ylabel("ASR"); ax[0, 1].legend(fontsize=6, ncol=2)
        ax[0, 1].set_title("FIG V2-12  latent-attack robustness curve")
        w = hr.groupby("family").asr.max().reindex(fam_order)
        ax[1, 0].barh(range(len(w)), w.values,
                      color=[COL[f] for f in w.index])
        ax[1, 0].set_yticks(range(len(w))); ax[1, 0].set_yticklabels(w.index)
        ax[1, 0].set_xlabel("WORST-CASE ASR over attack magnitude (lower better)")
        ax[1, 0].set_title("FIG V2-13  worst-scale robustness")
        sfe = te[(te.kind == "safe") & (te.regime == regime)]
        fr = sfe.groupby("family").refusal.mean()
        asr = hr.groupby("family").asr.mean()
        common = [f for f in fam_order if f in fr.index and f in asr.index]
        cx = fr.reindex(common).values; cy = 1 - asr.reindex(common).values
        ax[1, 1].scatter(cx, cy, c=[COL[f] for f in common], s=60, zorder=3)
        for f, x_, y_ in zip(common, cx, cy):
            ax[1, 1].annotate(f.replace("_", " "), (x_, y_), fontsize=6,
                              xytext=(3, 3), textcoords="offset points")
        pf = pareto_front(cx, cy)
        if len(pf) > 1:
            o = np.argsort(cx[pf]); ax[1, 1].plot(cx[pf][o], cy[pf][o], "k--", lw=1,
                                                   label="Pareto front")
            ax[1, 1].legend()
        ax[1, 1].set_xlabel("benign false-refusal rate (XSTest safe)  →  cost")
        ax[1, 1].set_ylabel("1 − ASR  →  safety")
        ax[1, 1].set_title("FIG V2-14  safety–utility Pareto frontier")
        save(fig, f"figV2_11_14_llm_{regime}.png")
        cap(f"FIG V2-11/12/13/14 [{regime}] — `figV2_11_14_llm_{regime}.png`",
            "Held-out attack templates and a continuous latent-attack sweep on "
            "the frozen test split. Regime A uses oracle harm labels (isolates "
            "the mechanism; benign cost is zero by construction), regime B uses "
            "the frozen learned detector (the only regime in which the Pareto "
            "panel is meaningful).")

    # V2-15 / V2-16
    fig, ax = plt.subplots(1, 2, figsize=(11, 3.6))
    e = h.groupby("family")[["int_mean", "int_energy"]].mean().reindex(fam_order)
    ax[0].bar(range(len(e)), e.int_mean.values, color=[COL[f] for f in e.index])
    ax[0].set_xticks(range(len(e))); ax[0].set_xticklabels(e.index, rotation=35, ha="right")
    ax[0].set_ylabel(r"realised mean $\|\Delta h\|$")
    ax[0].set_title("FIG V2-15  realised intervention (analytic budget matched)")
    KEY = ["regime", "attack", "eps_pct", "pid"]
    pv = h.groupby(KEY + ["family"]).asr.mean().unstack("family")
    rows = []
    for c in [f for f in fam_order if f not in ("L7_cantor",)]:
        sub = pv[["L7_cantor", c]].dropna()
        if len(sub) < 10: continue
        st = paired_bootstrap(-sub["L7_cantor"].values, -sub[c].values, seed=9)
        rows.append((c, st["mean_diff"], st["ci_lo"], st["ci_hi"], st["n"]))
    if rows:
        nm = [r[0] for r in rows]; md = [r[1] for r in rows]
        lo = [r[1] - r[2] for r in rows]; hi = [r[3] - r[1] for r in rows]
        y = np.arange(len(nm))
        ax[1].errorbar(md, y, xerr=[lo, hi], fmt="o", color="#1f77b4", capsize=3)
        ax[1].axvline(0, color="k", lw=1)
        ax[1].set_yticks(y); ax[1].set_yticklabels(nm)
        ax[1].set_xlabel(r"$\Delta(-\mathrm{ASR})$: Cantor $-$ control (>0 = Cantor safer)")
        ax[1].set_title("FIG V2-16  paired difference on the frozen test")
    save(fig, "figV2_15_16_budget_paired.png")
    cap("FIG V2-15/16 — `figV2_15_16_budget_paired.png`",
        "Left: realised intervention norm. The analytic budget "
        r"$\int c\,dr = B_{total}$ is identical by construction; what differs is "
        "how much of it a trajectory actually spends. Right: the pre-registered "
        "primary comparison, paired on (regime, attack, eps, prompt).")

# ------------------------------------------------ V2-17/18 POST-HOC diagnosis
pf = V2_RAW / f"llm_posthoc_degradation_{mk}.csv"
if pf.exists():
    pd_ = pd.read_csv(pf)
    hh = pd_[pd_.kind == "harmful"]; ss2 = pd_[pd_.kind == "safe"]
    g = hh.groupby("family").agg(int_rel=("int_rel_actnorm", "mean"),
                                 refusal=("refusal", "mean"),
                                 coh=("coherence", "mean"),
                                 cref=("coherent_refusal", "mean")).reindex(
                                     [f for f in ORDER if f in set(hh.family)])
    gs2 = ss2.groupby("family").agg(fr=("coherent_refusal", "mean")).reindex(g.index)
    fig, ax = plt.subplots(1, 3, figsize=(13, 3.6))
    x = np.arange(len(g))
    ax[0].bar(x - .2, g.refusal, .4, label="lexical refusal", color="#aaaaaa")
    ax[0].bar(x + .2, g.cref, .4, label="COHERENT refusal", color="#1f77b4")
    ax[0].set_xticks(x); ax[0].set_xticklabels(g.index, rotation=35, ha="right")
    ax[0].legend(); ax[0].set_ylabel("rate on harmful prompts")
    ax[0].set_title("FIG V2-18a  refusal vs coherent refusal")
    ax[1].scatter(g.int_rel, g.coh, c=[COL[f] for f in g.index], s=70, zorder=3)
    for f, a_, c_ in zip(g.index, g.int_rel, g.coh):
        ax[1].annotate(f.replace("_", " "), (a_, c_), fontsize=6,
                       xytext=(3, 3), textcoords="offset points")
    ax[1].set_xlabel(r"intervention norm / $\|h\|$"); ax[1].set_ylabel("output coherence")
    ax[1].set_title("FIG V2-18b  large pushes destroy the output")
    ax[2].scatter(gs2.fr, g.cref, c=[COL[f] for f in g.index], s=70, zorder=3)
    for f, a_, c_ in zip(g.index, gs2.fr, g.cref):
        ax[2].annotate(f.replace("_", " "), (a_, c_), fontsize=6,
                       xytext=(3, 3), textcoords="offset points")
    pfr = pareto_front(gs2.fr.values, g.cref.values)
    o = np.argsort(gs2.fr.values[pfr])
    ax[2].plot(gs2.fr.values[pfr][o], g.cref.values[pfr][o], "k--", lw=1,
               label="Pareto front")
    ax[2].legend()
    ax[2].set_xlabel("benign coherent FALSE refusal  →  cost")
    ax[2].set_ylabel("harmful coherent refusal  →  safety")
    ax[2].set_title("FIG V2-14b  POST-HOC coherent-refusal Pareto")
    save(fig, "figV2_17_18_posthoc.png")
    cap("FIG V2-18 / V2-14b — `figV2_17_18_posthoc.png`",
        "POST-HOC diagnosis of the degenerate frozen endpoint. Left: the "
        "lexical refusal rate overstates several controllers because incoherent "
        "output sometimes contains refusal fragments. Middle: coherence falls "
        "as the intervention approaches the activation norm -- L1, L6 and L7 all "
        "push at 60-75% of ||h||, far outside the linear steering regime. "
        "Right: on the coherence-corrected Pareto, no barrier controller "
        "dominates; L3_periodic (a matched-width CONTROL) gives the best safety "
        "per unit intervention, and constant steering buys the highest refusal "
        "at 100% benign false refusal.")

with open(FIG / "CAPTIONS.md", "w") as f:
    f.write("\n".join(CAP))
print("captions ->", FIG / "CAPTIONS.md")
