"""All V3 figures. Regenerated from results/v3/raw/*.csv only."""
import sys, json
sys.path.insert(0, "llm/src")
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from cantor_guard_v3.io3 import FIG3, V3_RAW
plt.rcParams.update({"figure.dpi": 150, "font.size": 8, "axes.grid": True,
                     "grid.alpha": .25, "axes.spines.top": False,
                     "axes.spines.right": False, "legend.fontsize": 7,
                     "axes.titlesize": 9})
CAP = ["# V3 figure captions\n\nRegenerated by `scripts/v3/generate_v3_figures.py`.\n"]
def cap(n, t): CAP.append(f"\n### {n}\n\n{t}\n")
def save(f, n): f.tight_layout(); f.savefig(FIG3/n, bbox_inches="tight"); plt.close(f); print("  ok", n)
ORD = ["L0_none","L1_constant","L2_narrow_central","L3_wide_central","L4_periodic",
       "L5_random","L6_shuffled","L7_center_anchored","L8_cantor","L9_minimax","L10_spline"]
COL = dict(zip(ORD, plt.cm.tab20(np.linspace(0,1,len(ORD)))))
COL["L8_cantor"] = "#d62728"; COL["L1_constant"] = "#1f77b4"

# ---------------------------------------------------------------- V3-03/04
bf = V3_RAW/"v3_boundary_shift_qwen2.5-0.5b-instruct.csv"
if bf.exists():
    sh = pd.read_csv(bf)
    fig, ax = plt.subplots(1,3, figsize=(13,3.4))
    p = sh.pivot_table(index="bin", columns="layer", values="delta_norm", aggfunc="mean")
    order = ["prefill","gen_1","gen_2-4","gen_5-8","gen_9-16","gen_17+"]
    p = p.reindex([o for o in order if o in p.index])
    im = ax[0].imshow(p.values, cmap="RdBu_r", vmin=-1.2, vmax=1.2, aspect="auto")
    ax[0].set_xticks(range(len(p.columns))); ax[0].set_xticklabels(p.columns)
    ax[0].set_yticks(range(len(p.index))); ax[0].set_yticklabels(p.index)
    ax[0].set_xlabel("layer"); plt.colorbar(im, ax=ax[0], label=r"$\Delta_{norm}$ ($\sigma$)")
    ax[0].set_title("FIG V3-03  boundary shift by token position")
    a = sh.delta_norm.abs()
    ax[1].hist(a, bins=30, color="#4c72b0", alpha=.85)
    for q,c,l in ((a.median(),"k","median %.2f"%a.median()),
                  (a.quantile(.95),"r","q95 %.2f"%a.quantile(.95))):
        ax[1].axvline(q, color=c, ls="--", lw=1.5, label=l)
    ax[1].set_xlabel(r"$|\Delta_{norm}|$ ($\sigma$)"); ax[1].set_ylabel("conditions")
    ax[1].legend(); ax[1].set_title("FIG V3-04  natural boundary-shift distribution")
    cf = V3_RAW/"v3_calibration_qwen2.5-0.5b-instruct.csv"
    if cf.exists():
        cd = pd.read_csv(cf)
        x = np.arange(len(cd))
        ax[2].bar(x-.2, cd.err_calibration, .4, label="calibration (in-sample)", color="#aaa")
        ax[2].bar(x+.2, cd.err_dev, .4, label="DEV (held out)", color="#c44e52")
        ax[2].set_xticks(x); ax[2].set_xticklabels(cd.method, rotation=20)
        ax[2].set_ylabel(r"residual boundary error ($\sigma$)"); ax[2].legend()
        ax[2].set_title("FIG V3-05  fixed vs dynamic calibration")
    save(fig, "figV3_03_05_boundary.png")
    cap("FIG V3-03/04/05 — `figV3_03_05_boundary.png`",
        "Left: the safety threshold moves by up to 1.65 sigma between the last "
        "prompt token and the first generated token (layer 4). Middle: the "
        "distribution of |Delta| over 180 (layer, attack, token-bin) conditions; "
        "median 0.34 sigma, q95 1.19 sigma. Right: token-bin calibration cuts "
        "the held-out boundary error by 28.9% versus V2's single fixed "
        "threshold, but 0.213 sigma remains.")

# ---------------------------------------------------------------- V3-06/07
sys.path.insert(0, "llm/src")
from cantor_guard.cantor_barrier import build_layout
n, E0 = 5, 1/5
r = np.linspace(0,1,60001)
fig, ax = plt.subplots(1,2, figsize=(11,3.3))
Ln = build_layout("L7_cantor", n, E0); Lm = build_layout("L7_cantor", n-1, E0)
ax[0].plot(r, Ln.field(r/3), lw=.8, label=r"$V'_n(r/3)$")
ax[0].plot(r, 1.5*Lm.field(r), lw=.8, ls="--", label=r"$\frac{3}{2}V'_{n-1}(r)$")
ax[0].legend(); ax[0].set_xlabel("$r$")
ax[0].set_title("FIG V3-06  Theorem S holds exactly for Cantor")
Ls = build_layout("L5_shuffled", n, E0, seed=3)
ax[1].plot(r, Ls.field(r/3), lw=.8, label=r"$V'_n(r/3)$ shuffled")
ax[1].plot(r, 1.5*Lm.field(r), lw=.8, ls="--", label=r"$\frac{3}{2}V'_{n-1}(r)$")
ax[1].legend(); ax[1].set_xlabel("$r$")
ax[1].set_title("FIG V3-07  and fails for a width-matched shuffle")
save(fig, "figV3_06_07_selfsim.png")
cap("FIG V3-06/07 — `figV3_06_07_selfsim.png`",
    "Theorem S: the Cantor barrier field is exactly scale-equivariant under the "
    "two Cantor contractions (relative residual 1e-13). A shuffled layout with "
    "the identical gap-width and energy multiset has residual 0.82-0.96. This "
    "is the one structural property that is NOT ordering-invariant.")

# ------------------------------------------------------------- V3-08..12, 17
sf = V3_RAW/"v3_synthetic_joint.csv"
if sf.exists():
    d = pd.read_csv(sf)
    tg = 0.60
    s = d[d.budget == tg]
    fig, ax = plt.subplots(2,2, figsize=(11,6.6))
    for k,(fam,t) in enumerate([("L2_narrow_central","central"),("L8_cantor","Cantor")]):
        sub = s[s.family==fam]
        M = sub.pivot_table(index="delta", columns="eps", values="safe_frac", aggfunc="mean")
        im = ax[0,k].imshow(M.values, cmap="viridis", vmin=0, vmax=1, aspect="auto",
                            origin="lower")
        ax[0,k].set_xticks(range(len(M.columns)))
        ax[0,k].set_xticklabels([f"{c:.2f}" for c in M.columns], rotation=40)
        ax[0,k].set_yticks(range(len(M.index)))
        ax[0,k].set_yticklabels([f"{i:+.3f}" for i in M.index])
        ax[0,k].set_xlabel(r"attack $\epsilon$"); ax[0,k].set_ylabel(r"boundary error $\Delta$")
        plt.colorbar(im, ax=ax[0,k], label="graded safety")
        ax[0,k].set_title(f"FIG V3-0{8+k}  R($\\Delta$,$\\epsilon$) — {t}")
    w = s.groupby(["family","delta","eps","attack"]).safe_frac.mean().reset_index()
    wm = w.groupby("family").safe_frac.min().reindex(ORD).dropna()
    ax[1,0].barh(range(len(wm)), wm.values, color=[COL[f] for f in wm.index])
    ax[1,0].set_yticks(range(len(wm))); ax[1,0].set_yticklabels(wm.index)
    ax[1,0].set_xlabel("worst-case graded robustness (higher better)")
    ax[1,0].set_title("FIG V3-17  minimax robustness at matched realised budget")
    for fam in ORD:
        sub = s[s.family==fam]
        if sub.empty: continue
        g = sub.groupby("delta").safe_frac.mean()
        ax[1,1].plot(g.index, g.values, "o-", ms=3, lw=1.2, label=fam, color=COL[fam])
    ax[1,1].set_xlabel(r"boundary error $\Delta$"); ax[1,1].set_ylabel("graded safety")
    ax[1,1].legend(fontsize=6, ncol=2)
    ax[1,1].set_title(r"FIG V3-12  degradation vs boundary error")
    save(fig, "figV3_08_17_robustness.png")
    cap("FIG V3-08/09/12/17 — `figV3_08_17_robustness.png`",
        "Joint boundary x attack uncertainty at matched REALISED intervention "
        "budget (+-2%). Top: robustness surfaces. Bottom left: the pre-registered "
        "primary endpoint -- constant steering is the most robust and Cantor is "
        "the least, barely above no intervention. Bottom right: state-dependent "
        "barriers degrade with |Delta| while constant steering does not, which is "
        "the mechanism.")

# ---------------------------------------------------------------- V3-19
mf = V3_RAW/"v3_mechanism.csv"
if mf.exists():
    m = pd.read_csv(mf)
    fig, ax = plt.subplots(1,2, figsize=(11,3.4))
    ca = m[m.family=="L8_cantor"]; ot = m[m.family!="L8_cantor"]
    ax[0].scatter(ot.selfsim, ot.R_worst, s=18, alpha=.6, color="#4c72b0", label="controls")
    ax[0].scatter(ca.selfsim, ca.R_worst, s=90, marker="*", color="#d62728", label="Cantor",
                  zorder=5)
    rr = np.corrcoef(m.selfsim, m.R_worst)[0,1]
    ax[0].set_xlabel("self-similarity score (Theorem S)")
    ax[0].set_ylabel("worst-case robustness"); ax[0].legend()
    ax[0].set_title(f"FIG V3-19a  self-similarity: r = {rr:+.3f}  (REJECTED)")
    ax[1].scatter(ot.max_weak_run, ot.R_worst, s=18, alpha=.6, color="#55a868", label="controls")
    ax[1].scatter(ca.max_weak_run, ca.R_worst, s=90, marker="*", color="#d62728",
                  label="Cantor", zorder=5)
    r2 = np.corrcoef(m.max_weak_run, m.R_worst)[0,1]
    ax[1].set_xlabel("longest unprotected stretch"); ax[1].set_ylabel("worst-case robustness")
    ax[1].legend(); ax[1].set_title(f"FIG V3-19b  coverage uniformity: r = {r2:+.3f}")
    save(fig, "figV3_19_mechanism.png")
    cap("FIG V3-19 — `figV3_19_mechanism.png`",
        "The mechanism test, run over 82 layouts rather than Cantor-versus-one. "
        "Self-similarity does not predict robustness (r = +0.147) even though "
        "Cantor scores 1.000 on it by Theorem S while every control scores below "
        "0.27; Cantor sits at the 36th percentile of the control distribution. "
        "What does predict robustness is the longest unprotected stretch "
        "(r = -0.680), i.e. plain coverage uniformity.")

with open(FIG3/"CAPTIONS.md","w") as f: f.write("\n".join(CAP))
print("captions ->", FIG3/"CAPTIONS.md")
