# ============================================================================
# All figures.  julia --project=. scripts/generate_all_figures.jl
#
# Every figure is regenerated from results/raw/*.csv, never from cached state,
# so `rm -rf figures && julia ... generate_all_figures.jl` reproduces the whole
# set. Captions with the full parameter context are written to
# figures/CAPTIONS.md.
# ============================================================================

using Plots, DataFrames, CSV, Statistics, Printf, Random, LaTeXStrings, Serialization
include(joinpath(@__DIR__, "..", "src", "CantorGate.jl"))
using .CantorGate
gr(); default(dpi = 160, fontfamily = "sans-serif", framestyle = :box,
             grid = true, gridalpha = 0.25, legendfontsize = 7,
             titlefontsize = 9, guidefontsize = 8, tickfontsize = 7,
             left_margin = 6Plots.mm, bottom_margin = 5Plots.mm,
             right_margin = 3Plots.mm, top_margin = 3Plots.mm)

const CAP = String[]
push!(CAP, "# Figure captions\n\nAll figures regenerated by `scripts/generate_all_figures.jl`.\n")
cap(name, text) = push!(CAP, "\n### $name\n\n$text\n")
save(p, name) = (savefig(p, figpath(name)); println("  ✓ $name"))
has(f) = isfile(rawpath(f))

"""Two-series grouped bar chart (avoids a StatsPlots dependency)."""
function grouped2(names, v1, v2, l1, l2; kwargs...)
    x = 1:length(names)
    p = bar(x .- 0.19, v1; bar_width = 0.36, label = l1, color = :steelblue,
            lc = :white, xticks = (x, names), kwargs...)
    bar!(p, x .+ 0.19, v2; bar_width = 0.36, label = l2, color = :indianred, lc = :white)
    return p
end

println("generating figures…")

# ------------------------------------------------------------------- FIG 1
let xs = range(0, 1; length = 12001)
    p = plot(xlabel = L"x", ylabel = L"C_n(x)", legend = :bottomright,
             title = "FIG 1  Finite-order Cantor staircase approximations",
             size = (860, 520), xlims = (0,1), ylims = (-0.02, 1.02))
    for (i, n) in enumerate(1:8)
        plot!(p, xs, cantor_staircase.(xs, n); label = "n = $n",
              lw = n ≤ 4 ? 1.7 : 1.0, alpha = 0.9,
              color = cgrad(:viridis)[(i-1)/7])
    end
    vspan!(p, [1/3, 2/3]; color = :palegreen, alpha = 0.18, label = "safe set S = [1/3, 2/3]")
    save(p, "fig01_cantor_staircase.png")
end
cap("FIG 1 — `fig01_cantor_staircase.png`",
    "C_n(x) for n = 1…8 on [0,1] (dimensionless state x, dimensionless value). " *
    "The shaded band is the safe set S = [1/3, 2/3], which is the level-1 removed " *
    "middle third and therefore a plateau of C_n for EVERY n ≥ 1.")

# ------------------------------------------------------------------- FIG 2
let
    ps = Any[]
    for n in 1:3
        xs = range(0, 1; length = 30001)
        ys = [cantor_gate(x, n) * (3/2)^n for x in xs]
        p = plot(xs, ys; seriestype = :steppre, fill = (0, 0.35), lw = 0.4,
                 legend = false, xlabel = L"x",
                 ylabel = n == 1 ? L"C'_n(x)" : "",
                 title = @sprintf("n=%d  |K_n|=%.4f  peak=(3/2)^%d=%.3f",
                                  n, (2/3)^n, n, (3/2)^n),
                 ylims = (0, (3/2)^n * 1.3), xlims = (0, 1))
        vspan!(p, [1/3, 2/3]; color = :palegreen, alpha = 0.25)
        push!(ps, p)
    end
    # support raster: which x are in K_n, for n = 1..10
    M = [cantor_gate(x, n) for n in 1:10, x in range(0, 1; length = 1500)]
    p4 = heatmap(range(0,1;length=1500), 1:10, M; c = [:white, :midnightblue],
                 colorbar = false, xlabel = L"x", ylabel = L"n",
                 title = "support of C'_n  (dark = pass, g_n = 1)", yticks = 1:10)
    vline!(p4, [1/3, 2/3]; color = :seagreen, lw = 1.2, label = "")
    p = plot(ps..., p4; layout = @layout([a b c; d]), size = (1150, 700),
             plot_title = "FIG 2  Derivative support and flat regions of C_n")
    save(p, "fig02_derivative_support.png")
end
cap("FIG 2 — `fig02_derivative_support.png`",
    "Top: C'_n for n = 1,2,3 — height (3/2)^n on a set of measure (2/3)^n, zero " *
    "elsewhere; the product is 1 for every n. Bottom: the pass set K_n as a " *
    "function of n; green lines mark ∂S. Note the safe set is white (blocked) at " *
    "every n, which is the content of Theorem 1.")

# ------------------------------------------------------------------- FIG 3
if has("numerical_integration.csv")
    ni = CSV.read(rawpath("numerical_integration.csv"), DataFrame)
    ex = CSV.read(rawpath("numerical_structure_aware.csv"), DataFrame)
    dxs = sort(unique(ni.dx)); ns = sort(unique(ni.n))
    p1 = plot(xlabel = L"n", ylabel = L"\hat{I}(n,\Delta x)", legend = :outerbottom,
              legend_columns = 3, title = "(a) estimate vs order", ylims = (0, 1.6))
    for dx in dxs
        s = sort(ni[ni.dx .== dx, :], :n)
        plot!(p1, s.n, s.I_mid; label = "Δx=$(dx)", marker = :circle, ms = 2.5, lw = 1.2)
    end
    plot!(p1, ex.n, ex.I_exact; label = "exact interval", color = :black, lw = 2.2)
    plot!(p1, ex.n, ex.I_adapt; label = "adaptive Simpson", color = :red, ls = :dash, lw = 1.6)
    hline!(p1, [1.0]; color = :green, ls = :dot, lw = 1.5, label = "analytic truth = 1")

    p2 = plot(xlabel = L"\Delta x", ylabel = L"E=|\hat{I}-1|", xscale = :log10,
              yscale = :log10, legend = :outerbottom, legend_columns = 6,
              title = "(b) error vs grid spacing")
    for n in ns
        s = sort(ni[ni.n .== n, :], :dx)
        plot!(p2, s.dx, max.(s.E_mid, 1e-8); label = "n=$n", marker = :circle, ms = 2)
    end

    M = [only(ni[(ni.n .== n) .& (ni.dx .== dx), :E_mid]) for dx in dxs, n in ns]
    p3 = heatmap(ns, 1:length(dxs), log10.(max.(M, 1e-8)); c = :inferno,
                 xlabel = L"n", ylabel = L"\Delta x",
                 yticks = (1:length(dxs), string.(dxs)),
                 title = "(c) log₁₀ E, midpoint rule", colorbar_title = " ")
    # ρ = 1 contour, i.e. Δx = 3^-n. The y axis is a categorical index over the
    # (roughly log-spaced) dxs, so interpolate the index in log Δx; points off the
    # sampled range are dropped rather than clamped to a misleading edge value.
    ρ1x, ρ1y = Float64[], Float64[]
    ld = log10.(dxs)
    for n in ns
        t = -n * log10(3.0)
        (t < ld[1] || t > ld[end]) && continue
        i = searchsortedlast(ld, t)
        i == length(ld) && (i -= 1)
        push!(ρ1x, n)
        push!(ρ1y, i + (t - ld[i]) / (ld[i+1] - ld[i]))
    end
    plot!(p3, ρ1x, ρ1y; color = :cyan, lw = 2.5, label = "ρ = 1  (Δx = 3⁻ⁿ)")

    p4 = scatter(ni.rho, max.(ni.E_mid, 1e-8); xscale = :log10, yscale = :log10,
                 group = ni.n, ms = 3.5, xlabel = L"\rho = \Delta x\cdot 3^n",
                 ylabel = L"E", legend = :outerbottom, legend_columns = 7,
                 legendtitle = "n", legendtitlefontsize = 7,
                 title = "(d) the error collapses onto ρ")
    vline!(p4, [1.0]; color = :red, ls = :dash, lw = 2, label = "ρ = 1")
    for q in (p1, p2, p4); plot!(q; bottom_margin = 12Plots.mm); end
    p = plot(p1, p2, p3, p4; layout = (2,2), size = (1300, 1020),
             plot_title = "FIG 3  Quadrature of C'_n (analytic truth ≡ 1)")
    save(p, "fig03_numerical_integration.png")
    cap("FIG 3 — `fig03_numerical_integration.png`",
        "(a) midpoint-rule estimate vs n for seven grid spacings, against the two " *
        "Δx-independent rules. (b) error vs Δx, log–log. (c) log₁₀ error heat map " *
        "with the ρ = 1 contour. (d) all 84 (n, Δx) cases collapse onto the single " *
        "dimensionless number ρ = Δx·3ⁿ: the error is negligible for ρ ≲ 0.1 and " *
        "O(1) for ρ ≳ 10. Analytic truth is 1 exactly at every n; every deviation " *
        "shown is a property of the quadrature rule.")
end

# ------------------------------------------------------------------- FIG 4
let α = 0.8, A = 1.5, ω = 4.0, h0 = 0.15, T = 30.0
    δ = sinusoid(A, ω)
    models = [("(A) no filter", NoGate(), :firebrick),
              ("(B) Cantor C₃",  cantor_interval_gate(3), :slateblue),
              ("(C) Cantor C₅",  cantor_interval_gate(5), :navy)]
    ps = Any[]
    for (name, g, c) in models
        ts, hs, gs = simulate_rk4(g, δ; α = α, h0 = h0, T = T, dt = 1e-3, save_every = 2)
        m = compute_metrics(ts, hs, gs)
        p = plot(ts, hs; color = c, lw = 0.8, label = "", ylabel = L"h(t)",
                 ylims = (-0.15, 1.15), xlims = (0, T),
                 title = @sprintf("%s   R_safe=%.1f%%   R_gate=%.2f%%   τ_S=%s",
                                  name, 100*m.R_safe, 100*m.R_gate, fmtf(m.tau_S,2)))
        hspan!(p, [1/3, 2/3]; color = :palegreen, alpha = 0.3, label = "S = [1/3, 2/3]")
        hline!(p, [0.5]; color = :gray, ls = :dot, lw = 0.8, label = "")
        plot!(p, ts, 0.5 .* gs .- 0.13; color = :orange, lw = 1.4,
              label = "gate g(h(t)) (offset)")
        push!(ps, p)
    end
    plot!(ps[3]; xlabel = L"t")
    p = plot(ps...; layout = (3,1), size = (1050, 800),
             plot_title = "FIG 4  Baseline reproduction: α=0.8, A=1.5, ω=4, h₀=0.15, T=30")
    save(p, "fig04_baseline_reproduction.png")
end
cap("FIG 4 — `fig04_baseline_reproduction.png`",
    "Reproduction of the original study (α=0.8, A=1.5, ω=4, h₀=0.15, T=30, RK4 " *
    "Δt=10⁻³). Reproduced occupancies 29.80 / 98.17 / 97.43 % vs the original " *
    "29.8 / 98.2 / 97.4 %. The orange trace is the gate value: for C₃ and C₅ it is " *
    "ZERO at t=0 because h₀=0.15 ∈ (1/9, 2/9) is already a flat interval, and it is " *
    "open for only 0.17 % / 0.13 % of the horizon.")

# --------------------------------------------------- FIG 5,6,7 from the sweep
if has("sweep_full.csv")
    sw = CSV.read(rawpath("sweep_full.csv"), DataFrame)
    ref = sw[(sw.A .== 1.5) .& (sw.omega .== 4.0) .& (sw.alpha .== 0.8), :]
    h0s = sort(unique(ref.h0)); ns = sort(unique(ref.n))
    M = [only(ref[(ref.n .== n) .& (ref.h0 .== h0), :R_safe]) for n in ns, h0 in h0s]

    pa = heatmap(h0s, ns, M; c = :viridis, clims = (0.25, 1.0),
                 xlabel = L"h_0", ylabel = L"n", yticks = ns,
                 colorbar_title = "R_safe",
                 title = "(a) all orders — n = 0 is the ungated system")
    vline!(pa, [1/3, 2/3]; color = :white, ls = :dash, lw = 1.2, label = "")
    # (b) gated orders only, colour scale set by the gated data itself
    gi = findall(>(0), ns)
    Mg = M[gi, :]
    pb = heatmap(h0s, ns[gi], Mg; c = :viridis,
                 clims = (quantile(vec(Mg), 0.01), 1.0),
                 xlabel = L"h_0", ylabel = L"n", yticks = ns[gi],
                 colorbar_title = "R_safe",
                 title = "(b) gated orders only (n ≥ 1), colour scale rescaled")
    vline!(pb, [1/3, 2/3]; color = :white, ls = :dash, lw = 1.2, label = "∂S")
    scatter!(pb, [0.15], [3]; m = (:star5, 10, :red), label = "original (h₀=0.15, C₃)")
    scatter!(pb, [0.15], [5]; m = (:star5, 10, :orange), label = "original (h₀=0.15, C₅)")
    p = plot(pa, pb; layout = (2,1), size = (1050, 820),
             plot_title = "FIG 5  Safe occupancy over (h₀, n)   A=1.5, ω=4, α=0.8")
    save(p, "fig05_h0_n_occupancy.png")
    cap("FIG 5 — `fig05_h0_n_occupancy.png`",
        "Safe-set occupancy R_safe on the (h₀, n) plane at the original operating " *
        "point. n = 0 is the ungated system. The two stars are the ONLY two cells " *
        "the original study measured. Occupancy is far from uniform in h₀, and rows " *
        "n ≥ 2 are not systematically brighter than n = 1.")

    Mτ = [begin v = only(ref[(ref.n .== n) .& (ref.h0 .== h0), :tau_S])
                isfinite(v) ? v : NaN end for n in ns, h0 in h0s]
    p = heatmap(h0s, ns, Mτ; c = :magma, xlabel = L"h_0", ylabel = L"n", yticks = ns,
                colorbar_title = "τ_S", clims = (0, quantile(filter(isfinite, vec(Mτ)), 0.98)),
                title = "FIG 6  First hitting time τ_S over (h₀, n)   A=1.5, ω=4, α=0.8",
                size = (1000, 480))
    vline!(p, [1/3, 2/3]; color = :cyan, ls = :dash, lw = 1.2, label = "∂S")
    scatter!(p, [0.15], [3]; m = (:star5, 9, :red), label = "original")
    save(p, "fig06_h0_n_hitting_time.png")
    cap("FIG 6 — `fig06_h0_n_hitting_time.png`",
        "First hitting time τ_S = inf{t : h(t) ∈ S}. White/NaN cells never reached S " *
        "within T = 30. Bright bands away from S are trapping regions: flat intervals " *
        "far from the safe set where the gate blocks the very disturbance that would " *
        "have carried the state into S.")

    # FIG 7 : A × ω phase diagrams for several n
    sel_n = [0, 1, 3, 5, 8, 10]
    As = sort(unique(sw.A)); ωs = sort(unique(sw.omega))
    ps = Any[]
    for n in sel_n
        s = sw[(sw.n .== n) .& (sw.alpha .== 0.8), :]
        M2 = [mean(s[(s.A .== A) .& (s.omega .== ω), :R_safe]) for A in As, ω in ωs]
        pp = heatmap(1:length(ωs), 1:length(As), M2; c = :viridis, clims = (0.2, 1.0),
                     xticks = (1:length(ωs), string.(ωs)),
                     yticks = (1:length(As), string.(As)),
                     xlabel = L"\omega", ylabel = n == 0 ? L"A" : "",
                     title = n == 0 ? "no filter" : "Cantor n=$n", colorbar = (n == 10))
        push!(ps, pp)
    end
    p = plot(ps...; layout = (2,3), size = (1250, 700),
             plot_title = "FIG 7  Robustness phase diagram over (A, ω), α=0.8, mean over 99 h₀")
    save(p, "fig07_A_omega_phase.png")
    cap("FIG 7 — `fig07_A_omega_phase.png`",
        "Mean R_safe over all 99 initial conditions, on the (A, ω) plane at α = 0.8. " *
        "The ungated system degrades sharply for large A and small ω (the disturbance " *
        "outruns the restoring force); every gated system is nearly flat, and the " *
        "gated panels are almost indistinguishable from one another.")

    # FIG 7b : α × A
    ps = Any[]
    αs = sort(unique(sw.alpha))
    for n in sel_n
        s = sw[(sw.n .== n) .& (sw.omega .== 4.0), :]
        M2 = [mean(s[(s.A .== A) .& (s.alpha .== α), :R_safe]) for A in As, α in αs]
        pp = heatmap(1:length(αs), 1:length(As), M2; c = :viridis, clims = (0.2, 1.0),
                     xticks = (1:length(αs), string.(αs)),
                     yticks = (1:length(As), string.(As)),
                     xlabel = L"\alpha", ylabel = n == 0 ? L"A" : "",
                     title = n == 0 ? "no filter" : "Cantor n=$n", colorbar = (n == 10))
        push!(ps, pp)
    end
    p = plot(ps...; layout = (2,3), size = (1250, 700),
             plot_title = "FIG 7b  Robustness phase diagram over (α, A), ω=4, mean over 99 h₀")
    save(p, "fig07b_alpha_A_phase.png")
    cap("FIG 7b — `fig07b_alpha_A_phase.png`",
        "As FIG 7 but on the (α, A) plane at ω = 4. The ungated system's occupancy " *
        "tracks the analytic prediction (2/π)·asin(√(α²+ω²)/(6A)).")

    # FIG 5b : distribution of R_safe by n (not just the mean)
    p = plot(xlabel = L"n", ylabel = L"R_{safe}", legend = :bottomright,
             title = "FIG 5b  Distribution of R_safe by order n over the FULL grid " *
                     "(196 020 runs)", size = (980, 520), ylims = (0, 1.03))
    for n in ns
        v = sw[sw.n .== n, :R_safe]
        q = quantile(v, [0.05, 0.25, 0.5, 0.75, 0.95])
        plot!(p, [n, n], [q[1], q[5]]; color = :gray, lw = 1.2, label = n == ns[1] ? "5–95 %" : "")
        plot!(p, [n, n], [q[2], q[4]]; color = :steelblue, lw = 7, label = n == ns[1] ? "IQR" : "")
        scatter!(p, [n], [q[3]]; m = (:circle, 5, :white), msc = :black,
                 label = n == ns[1] ? "median" : "")
        scatter!(p, [n], [mean(v)]; m = (:diamond, 5, :crimson), label = n == ns[1] ? "mean" : "")
    end
    save(p, "fig05b_n_distribution.png")
    cap("FIG 5b — `fig05b_n_distribution.png`",
        "R_safe distribution for each order n over all 196 020 sweep cells. Means, " *
        "medians and IQRs are shown because the mean alone hides that every gated " *
        "order has a long lower tail. The mean is NOT monotone in n: it peaks at " *
        "n = 1 and has a minimum near n = 7.")
end

# ------------------------------------------------- FIG 8,9,10 from the ablation
if has("ablation_main.csv")
    ab = CSV.read(rawpath("ablation_main.csv"), DataFrame)
    ns = sort(unique(ab[ab.n .> 0, :n]))
    fams = ["G1_cantor", "G2_random", "G3_periodic", "G4_central", "G5_shuffled"]
    cols = Dict("G1_cantor"=>:crimson, "G2_random"=>:steelblue, "G3_periodic"=>:seagreen,
                "G4_central"=>:darkorange, "G5_shuffled"=>:purple)
    means = Dict(f => [mean(ab[(ab.gate_family .== f) .& (ab.n .== n), :R_safe]) for n in ns]
                 for f in fams)
    # y-range set by the n ≥ 2 data: G2 at n = 1 is a genuine outlier (0.841,
    # two random intervals of width 1/3 usually miss S) and is annotated instead
    # of being allowed to compress every other curve into a flat line.
    allv = vcat([means[f][2:end] for f in fams]...)
    p1 = plot(xlabel = L"n", ylabel = "mean R_safe", legend = :bottomleft,
              title = "(a) mean over 225 conditions (ribbon = ±1 SEM)", xticks = ns,
              ylims = (minimum(allv) - 0.0025, maximum(allv) + 0.0035))
    for f in fams
        # ±1 standard error of the MEAN. The raw sd is a spread across
        # heterogeneous (h0, A, ω) conditions, not an uncertainty on the mean.
        sem = [std(ab[(ab.gate_family .== f) .& (ab.n .== n), :R_safe]) /
               sqrt(count((ab.gate_family .== f) .& (ab.n .== n))) for n in ns]
        plot!(p1, ns, means[f]; ribbon = sem, fillalpha = 0.18, label = f,
              color = cols[f], lw = 2, marker = :circle, ms = 3)
    end
    annotate!(p1, 4.6, maximum(allv) + 0.0022,
              text("G2 at n=1 is 0.841, off scale: two width-1/3 intervals usually miss S",
                   6, :left, :steelblue))
    p2 = plot(xlabel = L"n", ylabel = "mean D_mean (lower better)", legend = :topleft,
              title = "(b) mean deviation", xticks = ns)
    for f in fams
        plot!(p2, ns, [mean(ab[(ab.gate_family .== f) .& (ab.n .== n), :D_mean]) for n in ns];
              label = f, color = cols[f], lw = 2, marker = :circle, ms = 3)
    end
    p3 = plot(xlabel = L"n", ylabel = "median τ_S (finite only)", legend = :topleft,
              title = "(c) first hitting time", xticks = ns)
    for f in fams
        plot!(p3, ns, [median(filter(isfinite, ab[(ab.gate_family .== f) .& (ab.n .== n), :tau_S]))
                       for n in ns]; label = f, color = cols[f], lw = 2, marker = :circle, ms = 3)
    end
    # (d) THE ablation statistic: where does Cantor sit inside the control
    # distribution? 50 % = indistinguishable from a matched random layout.
    p4 = plot(xlabel = L"n", ylabel = "percentile rank of G1 (%)", legend = :topright,
              title = "(d) Cantor's rank within the matched-control distribution",
              xticks = ns, ylims = (0, 100))
    if isfile(tabpath("ablation_delta_grid.csv"))
        dgx = CSV.read(tabpath("ablation_delta_grid.csv"), DataFrame)
        for (ctrl, c) in (("G2_random", :steelblue), ("G5_shuffled", :purple))
            plot!(p4, ns, [mean(dgx[(dgx.control .== ctrl) .& (dgx.n .== n), :pct_rank])
                           for n in ns]; label = "vs $ctrl", color = c, lw = 2,
                  marker = :circle, ms = 3)
        end
    end
    hline!(p4, [50.0]; color = :black, ls = :dash, lw = 1.5,
           label = "50 % = indistinguishable")
    annotate!(p4, 1.2, 92, text("above 50 %: the Cantor arrangement helps", 6, :left, :gray30))
    annotate!(p4, 1.2, 8, text("below 50 %: the control arrangement is better", 6, :left, :gray30))
    plot!(p4; legend = :bottomright)
    p = plot(p1, p2, p3, p4; layout = (2,2), size = (1250, 880),
             plot_title = "FIG 8  Ablation: five gate families at IDENTICAL pass measure (2/3)ⁿ")
    save(p, "fig08_ablation_families.png")
    cap("FIG 8 — `fig08_ablation_families.png`",
        "All five families block exactly the same amount of state space, 1−(2/3)ⁿ. " *
        "Pooled over 25 h₀ × 3 A × 3 ω at α = 0.8; G2 and G5 additionally averaged " *
        "over 30 random layouts each. Ribbons are ±σ/4. Any separation between " *
        "curves is an effect of ARRANGEMENT, not of measure.")

    if isfile(tabpath("ablation_delta_grid.csv"))
        dg = CSV.read(tabpath("ablation_delta_grid.csv"), DataFrame)
        ps = Any[]
        for ctrl in ("G2_random", "G5_shuffled")
            s = dg[dg.control .== ctrl, :]
            local h0s = sort(unique(s.h0)); nns = sort(unique(s.n))
            local M = [mean(s[(s.n .== n) .& (s.h0 .== h0), :delta]) for n in nns, h0 in h0s]
            lim = maximum(abs, filter(isfinite, vec(M)))
            pp = heatmap(h0s, nns, M; c = :RdBu, clims = (-lim, lim),
                         xlabel = L"h_0", ylabel = L"n", yticks = nns,
                         title = "ΔR = Cantor − $(ctrl)", colorbar_title = "ΔR_safe")
            vline!(pp, [1/3, 2/3]; color = :black, ls = :dash, lw = 1, label = "")
            push!(ps, pp)
        end
        p = plot(ps...; layout = (2,1), size = (1050, 760),
                 plot_title = "FIG 9  Cantor minus measure-matched control (red = Cantor better)")
        save(p, "fig09_cantor_minus_control.png")
        cap("FIG 9 — `fig09_cantor_minus_control.png`",
            "ΔR_safe = R(Cantor) − mean over 30 measure-matched control layouts, " *
            "averaged over A and ω, on the (h₀, n) plane. Red = Cantor better, blue = " *
            "control better. A structural advantage would show as a uniformly red map.")

        # FIG 10 : seed distributions at representative conditions
        ps = Any[]
        for (i, n) in enumerate([2, 4, 6, 8])
            s = ab[(ab.n .== n) .& (ab.A .== 1.5) .& (ab.omega .== 4.0), :]
            rc = s[s.gate_family .== "G1_cantor", :R_safe]
            pp = plot(xlabel = "R_safe", ylabel = "density", title = "n = $n",
                      legend = i == 1 ? :topleft : false)
            for (f, c) in (("G2_random", :steelblue), ("G5_shuffled", :purple))
                v = s[s.gate_family .== f, :R_safe]
                histogram!(pp, v; bins = 40, normalize = :pdf, alpha = 0.45,
                           color = c, label = f, lc = nothing)
            end
            vline!(pp, [mean(rc)]; color = :crimson, lw = 2.5, label = "G1 Cantor (mean)")
            push!(ps, pp)
        end
        p = plot(ps...; layout = (2,2), size = (1150, 780),
                 plot_title = "FIG 10  Cantor against the DISTRIBUTION of matched random layouts " *
                              "(30 seeds × 25 h₀, A=1.5, ω=4)")
        save(p, "fig10_seed_distribution.png")
        cap("FIG 10 — `fig10_seed_distribution.png`",
            "Cantor is never compared to a single random draw. Histograms are the " *
            "pooled R_safe of 30 random layouts × 25 initial conditions; the red line " *
            "is the Cantor mean over the same initial conditions.")
    end
end

# ------------------------------------------------------------------ FIG 11
if has("ablation_smooth.csv")
    sm = CSV.read(rawpath("ablation_smooth.csv"), DataFrame)
    βs = sort(unique(sm.beta))
    p1 = plot(xlabel = L"\beta", ylabel = "mean R_safe", xscale = :log10,
              legend = :bottomright, title = "(a) occupancy vs smoothness")
    for n in sort(unique(sm.n)), A in sort(unique(sm.A))
        s = sm[(sm.n .== n) .& (sm.A .== A), :]
        plot!(p1, βs, [mean(s[s.beta .== β, :R_safe]) for β in βs];
              label = "n=$n, A=$A", lw = 1.8, marker = :circle, ms = 3)
    end
    if has("ablation_main.csv")
        ab = CSV.read(rawpath("ablation_main.csv"), DataFrame)
        for n in sort(unique(sm.n))
            hline!(p1, [mean(ab[(ab.gate_family .== "G1_cantor") .& (ab.n .== n), :R_safe])];
                   ls = :dash, label = "hard n=$n")
        end
    end
    xs = range(0.28, 0.72; length = 4000)
    p2 = plot(xlabel = L"h", ylabel = L"g(h)", title = "(b) gate near ∂S", legend = :topright)
    base = cantor_interval_gate(3)
    plot!(p2, xs, [gate_value(base, x) for x in xs]; color = :black, lw = 2, label = "hard")
    for β in (5.0, 25.0, 100.0, 1000.0)
        plot!(p2, xs, [gate_value(SmoothGate(base, β), x) for x in xs];
              lw = 1.5, label = "β = $(Int(β))")
    end
    vline!(p2, [1/3, 2/3]; color = :seagreen, ls = :dash, lw = 1.5, label = "∂S")
    p3 = plot(xlabel = L"\beta", ylabel = L"g_\beta(1/3)", xscale = :log10,
              title = "(c) gate ON the boundary is PINNED at ~1/2", legend = :topright)
    bb = [10.0^k for k in 0:0.25:4]
    plot!(p3, bb, [gate_value(SmoothGate(base, β), 1/3) for β in bb]; lw = 2.5,
          color = :crimson, label = L"g_\beta(1/3)")
    hline!(p3, [0.5]; color = :gray, ls = :dot, label = "1/2")
    p4 = plot(xlabel = "Nagumo margin  α/6 − A·g_β(∂S)", ylabel = "mean R_safe",
              title = "(d) Theorem 2 margin vs measured occupancy", legend = :bottomright)
    scatter!(p4, sm.invariance_margin, sm.R_safe; ms = 2, alpha = 0.25,
             color = :steelblue, label = "individual runs")
    vline!(p4, [0.0]; color = :red, lw = 2, ls = :dash, label = "guarantee boundary")
    p = plot(p1, p2, p3, p4; layout = (2,2), size = (1250, 900),
             plot_title = "FIG 11  Hard vs smooth Cantor gate (G6)")
    save(p, "fig11_hard_vs_smooth.png")
    cap("FIG 11 — `fig11_hard_vs_smooth.png`",
        "(a) occupancy vs β. (b) the gate profile near ∂S. (c) g_β(1/3) → 1/2 as " *
        "β → ∞ because 1/3 is an ENDPOINT of a pass interval, so the Theorem-2 " *
        "guarantee A·g(∂S) < α/6 can never be met for A ≥ α/3 no matter how sharp " *
        "the gate. (d) every run to the right of the red line is guaranteed invariant; " *
        "the guarantee is sufficient, not necessary.")
end

# ------------------------------------------------------------- FIG 12,13,14
if has("neural_training.csv")
    ht = CSV.read(rawpath("neural_training.csv"), DataFrame)
    labs = unique(ht.model)
    p1 = plot(xlabel = "iteration", ylabel = "training loss (MSE)", yscale = :log10,
              legend = :topright, title = "(a) training curves")
    for l in labs
        s = ht[ht.model .== l, :]
        plot!(p1, s.iter, s.loss; label = l, lw = 1.4)
    end
    p2 = plot(xlabel = "iteration", ylabel = L"\|\nabla_\theta L\|_2", yscale = :log10,
              legend = false, title = "(b) gradient norm")
    for l in labs
        s = ht[ht.model .== l, :]
        plot!(p2, s.iter, max.(s.gnorm, 1e-12); lw = 1.2)
    end
    p = plot(p1, p2; layout = (1,2), size = (1250, 480),
             plot_title = "FIG 12  Neural ODE training (identical initialisation, " *
                          "identical data, 300 Adam iterations)")
    save(p, "fig12_neural_training.png")
    cap("FIG 12 — `fig12_neural_training.png`",
        "Every gate variant is trained from the SAME network initialisation on the " *
        "SAME sinusoidal training distribution. Loss is the tracking MSE against the " *
        "clean reference trajectory of dh/dt = −1.2(h−½) − 2(h−½)³.")
end

if has("neural_benchmark.csv")
    nb = CSV.read(rawpath("neural_benchmark.csv"), DataFrame)
    labs = unique(nb.model)
    short(l) = replace(l, "neural_" => "")
    idm  = [mean(nb[(nb.model .== l) .& (nb.split .== "ID"),  :R_safe]) for l in labs]
    oodm = [mean(nb[(nb.model .== l) .& (nb.split .== "OOD"), :R_safe]) for l in labs]
    p1 = grouped2(short.(labs), idm, oodm, "TEST-ID", "TEST-OOD";
                  ylabel = "mean R_safe", xrotation = 40, legend = :bottomright,
                  title = "(a) occupancy, in- vs out-of-distribution",
                  ylims = (0.95, 1.0))
    idms  = [mean(nb[(nb.model .== l) .& (nb.split .== "ID"),  :mse]) for l in labs]
    oodms = [mean(nb[(nb.model .== l) .& (nb.split .== "OOD"), :mse]) for l in labs]
    p2 = grouped2(short.(labs), idms, oodms, "TEST-ID", "TEST-OOD";
                  ylabel = "tracking MSE vs clean reference", xrotation = 40,
                  legend = :topleft, title = "(b) tracking error vs the clean reference",
                  ylims = (0, 1.15 * maximum(vcat(idms, oodms))))
    kinds = unique(nb[nb.split .== "OOD", :kind])
    M = [mean(nb[(nb.model .== l) .& (nb.kind .== k), :R_safe]) for l in labs, k in kinds]
    p3 = heatmap(kinds, short.(labs), M; c = :viridis,
                 clims = (minimum(M), 1.0), xrotation = 40,
                 title = "(c) R_safe by OOD family — only amplitude extrapolation separates them",
                 colorbar_title = "R_safe")
    # (d) the solver cross-check: chattering is caused by switching surfaces
    # sitting near the LEARNED equilibrium, which the Cantor gate cannot have
    # inside S (Theorem 1) but a random measure-matched layout can.
    p4 = plot(xlabel = "switching surfaces inside S", ylabel = "adaptive-solver failures (%)",
              title = "(d) chattering vs gate geometry inside S", legend = :topleft,
              xlims = (-0.5, 5.5), ylims = (-5, 100))
    if has("neural_solver_crosscheck.csv")
        cc = CSV.read(rawpath("neural_solver_crosscheck.csv"), DataFrame)
        gates_d = Dict("neural_cantor_n3" => cantor_interval_gate(3),
                       ("neural_random_n3_s$(i)" => random_matched_gate(3,
                            Xoshiro(seed_for("node_random", 3, i))) for i in 1:3)...)
        xs = Float64[]; ys = Float64[]; ls = String[]
        for (l, g) in gates_d
            haskey(gates_d, l) || continue
            surf = count(x -> 1/3 < x < 2/3, vcat(g.los, g.his))
            sc = cc[cc.model .== l, :]
            isempty(sc) && continue
            push!(xs, surf); push!(ys, 100*count(.!sc.adaptive_ok)/nrow(sc))
            push!(ls, short(l))
        end
        scatter!(p4, xs, ys; ms = 8, color = :crimson, label = "")
        for i in eachindex(xs)
            annotate!(p4, xs[i], ys[i] + 7, text(ls[i], 7, :center))
        end
    end
    p = plot(p1, p2, p3, p4; layout = @layout([a b; c d]), size = (1400, 1000),
             plot_title = "FIG 13  Neural ODE: seen vs unseen perturbations")
    save(p, "fig13_neural_id_vs_ood.png")
    cap("FIG 13 — `fig13_neural_id_vs_ood.png`",
        "TEST-ID = fresh sinusoids from the training distribution (A∈[0.5,1.5], " *
        "ω∈[2,6]); TEST-OOD = square, chirp, multi-frequency, impulse train, OU " *
        "noise, piecewise-random, amplitude extrapolation A=3, frequency " *
        "extrapolation ω=16 and an adversarial search — all fixed before training.")
end

# FIG 14 : representative unseen trajectories
if isfile(procpath("trained_params.jls"))
    D = deserialize(procpath("trained_params.jls"))
    nvf, _ = init_nvf(Xoshiro(1); width = Int(D["width"]), depth = Int(D["depth"]),
                      T = Float64(D["T"]))
    P = D["params"]
    picks = filter(l -> l in keys(P),
                   ["neural_none", "neural_cantor_n3", "neural_random_n3_s1",
                    "neural_smooth_b50"])
    gates = Dict("neural_none" => NoGate(),
                 "neural_cantor_n3" => cantor_interval_gate(3),
                 "neural_random_n3_s1" => random_matched_gate(3, Xoshiro(seed_for("node_random",3,1))),
                 "neural_smooth_b50" => SmoothGate(cantor_interval_gate(3), 50.0))
    tests = [("square (OOD)",        square_wave(1.0, 4.0)),
             ("chirp (OOD)",         chirp(1.0, 0.5, 20.0, 20.0)),
             ("A = 3 extrapolation", sinusoid(3.0, 4.0)),
             ("OU noise (OOD)",      ou_noise(1.0, 20.0, 1.0, 2.0, 0.005, 11))]
    ps = Any[]
    for (tn, δ) in tests
        pp = plot(xlabel = "t", ylabel = "h(t)", title = tn, legend = (tn == tests[1][1]),
                  ylims = (-0.1, 1.1))
        hspan!(pp, [1/3, 2/3]; color = :palegreen, alpha = 0.3, label = "S")
        ts0, href = reference_trajectory([0.2], 20.0, 0.005, 1)
        plot!(pp, ts0, href[:,1]; color = :black, ls = :dash, lw = 2, label = "clean reference")
        for l in picks
            ts, hs, _ = evaluate_neural_ode(nvf, P[l], gates[l], δ; h0 = 0.2, T = 20.0)
            plot!(pp, ts, hs; lw = 1.3, label = replace(l, "neural_" => ""))
        end
        push!(ps, pp)
    end
    p = plot(ps...; layout = (2,2), size = (1250, 800),
             plot_title = "FIG 14  Trained Neural ODEs under UNSEEN perturbations (h₀ = 0.2)")
    save(p, "fig14_ood_trajectories.png")
    cap("FIG 14 — `fig14_ood_trajectories.png`",
        "Trained f_θ evaluated with the adaptive Tsit5 solver on four disturbances " *
        "never seen in training. The dashed black curve is the clean reference " *
        "trajectory the models were trained to track.")
end

open(figpath("CAPTIONS.md"), "w") do io; print(io, join(CAP, "\n")); end
println("\nfigures → ", figpath("")); println("captions → ", figpath("CAPTIONS.md"))
